/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testAppReternHelloWorld() {
        App classUnderTest = new App();
        assertNotNull("Hello World", classUnderTest.getGreeting());
    }
}
